# ********RoostGPT********

# Test generated by RoostGPT for test karateTest using AI Type Open AI and AI Model gpt-4
# 
# Feature file generated for /accounts_post for http method type POST 
# RoostTestHash=53e96f9805
# 
# 

# ********RoostGPT********
Feature: Accounts API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:8080')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * configure headers = { 'commit-hash': '#(authToken)' }

  Scenario Outline: Create new Account
    Given path '/accounts'
    And request { email: '<email>' }
    When method post
    Then match responseStatus == <status>
    And match responseHeaders['api-version'] == '1.0.0'
    And match responseHeaders['commit-hash'] == '#string'
    * def responseSchema =
      """
      {
        "required": ["email"],
        "properties": {
          "email": {
            "type": "string",
            "format": "email",
            "pattern": "^(([^<>()[\\]\\\\.,;:\\s@\\\"]+(\\.[^<>()[\\]\\\\.,;:\\s@\\\"]+)*)|(\\\".+\\\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$"
          }
        }
      }
      """
    And match response == responseSchema

    Examples:
      | email           | status |
      | 'test@test.com' |    201 |
      | 'invalid_email' |    400 |
