// ********RoostGPT********
/*
Test generated by RoostGPT for test ZBIO-4912-Rest-Assured-Test using AI Type Open AI and AI Model gpt-4

Test generated for /kvk/zoeken_get for http method type GET in rest-assured framework

RoostTestHash=2acea70323


*/

// ********RoostGPT********
package com.mycompany.app.RoostTest;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.junit.Assert.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.util.List;
import org.hamcrest.MatcherAssert;
import static org.hamcrest.Matchers.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class zoekenGetTest {

    List<Map<String, String>> envList = new ArrayList<>();


    @Before
    public void setUp() {
      TestdataLoader dataloader = new TestdataLoader();
      envList = dataloader.loadData("src/test/java/com/mycompany/app/RoostTest/zoekenGetTest.csv");
    }

  
    @Test  
    public void zoekenGet_Test() {
        this.setUp();
        for (Map<String, String> map : envList) {
          RestAssured.baseURI = map.get("BASE_URL");  
  
                Response response = given()
				.pathParam("kvkNummer", map.get("kvkNummer") != null ? map.get("kvkNummer") : "")
				.pathParam("vestigingsnummer", map.get("vestigingsnummer") != null ? map.get("vestigingsnummer") : "")
				.pathParam("handelsnaam", map.get("handelsnaam") != null ? map.get("handelsnaam") : "")
				.header("Token", map.get("API_KEY"))
                .when()
                .get("/kvk/zoeken")  
                .then() 
                .extract().response();    
         
                if (response.statusCode() == 200) {
					System.out.println("Description: successful operation");
				}
  
            }  
    }
}
